name: Output

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
      - run: echo "::debug::Test"
      - run: echo "::warning::Test"
      - run: echo "::error::Test"
      
